# DEBUG = -O0 -g

CFLAGS_AUX = -lrt
TOPDIR = ../..
EXECS = posixmq_create posixmq_unlink posixmq_getattr posixmq_send \
	posixmq_receive posixmq_notify_sig posixmq_notify_thread

.include "$(TOPDIR)/bsdman2.mk"
