/*-
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Copyright (c) 2025 Jianping Duan <static.integer@hotmail.com>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the University nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 */
#include "unibsd.h"
#include <syslog.h>
#include <getopt.h>

static void usage_info(const char *);

int
main(int argc, char *argv[])
{
	int options = 0, level = LOG_INFO;
	const char *optstr = "l:pe";
	int opt;

	extern char *optarg;
	extern int optind;

	while ((opt = getopt(argc, argv, optstr)) != -1)
		switch (opt) {
			case 'l':
				/*
				 * LOG_ALERT:
				 *	A condition that should be corrected immediately, such as a
				 *	corrupted system database.
				 *
				 * LOG_CRIT:
				 *	Critical conditions, e.g., hard device errors.
				 *
				 * LOG_DEBUG:
				 *	Messages that contain information normally of use only when
				 *	debugging a program.
				 *
				 * LOG_ERR:
				 *	Errors.
				 *
				 * LOG_INFO:
				 *	Informational messages.
				 *
				 * LOG_EMERG:
				 *	A panic condition. This is normally broadcast to all users.
				 *
				 * LOG_NOTICE:
				 *	Conditions that are not error conditions, but should
				 *	possibly be handled specially.
				 *
				 * LOG_WARNING:
				 *	Warning messages.
				 */
				switch (optarg[0]) {
					case 'a': level = LOG_ALERT; break;
					case 'c': level = LOG_CRIT; break;
					case 'd': level = LOG_DEBUG; break;
					case 'e': level = LOG_ERR; break;
					case 'i': level = LOG_INFO; break;
					case 'm': level = LOG_EMERG; break;
					case 'n': level = LOG_NOTICE; break;
					case 'w': level = LOG_WARNING; break;
					default: errmsg_exit1("Bad facility, %c\n", optarg[0]);
				}
				break;
			/*
			 * LOG_PID:
			 *	Log the process id with each message: useful for
			 *	identifying instantiations of daemons. On FreeBSD, this
			 *	option is enabled by default and cannot be disabled.
			 *
			 * LOG_PERROR:
			 *	Write the message to standard error output as well to the
			 *	system log.
			 *
			 * More log options see syslog(3).
			 */
			case 'p':
				options |= LOG_PID;
				break;
			case 'e':
				options |= LOG_PERROR;
				break;
			default:
				fprintf(stderr, "Bad option.\n");
				usage_info(argv[0]);
		}
	
	if (argc != optind + 1)
		usage_info(argv[0]);

	/*
	 * The openlog() function provides for more specialized processing of the
	 * messages sent by syslog() and vsyslog(). The ident argument is a string
	 * that will be prepended to every message. It may be formatted as ident[N]
	 * in which case decimal number N replaces the process id within messages.
	 * The logopt argument is a bit field specifying logging options, which is
	 * formed by OR'ing one or more of the following values:
	 * 
	 * The syslog() function writes message to the system message logger. The
	 * message is then written to the system console, log files, logged-in
	 * users, or forwarded to other machines as appropriate. 
	 *
	 * The closelog() function can be used to close the log file.
	 *
	 * LOG_USER:
	 *	Messages generated by random user processes. This is the
	 *	default facility identifier if none is specified.
	 *	
	 * More other facilities, see syslog(3).
	 */
	openlog(argv[0], options, LOG_USER);
	syslog(LOG_USER | level, "%s", argv[optind]);
	closelog();

	exit(EXIT_SUCCESS);
}

static void
usage_info(const char *pname)
{
	fprintf(stderr, "Usage: %s [-p] [-e] [-l level] \"message\"\n", pname);
    fprintf(stderr, "\t-p  log PID\n");
    fprintf(stderr, "\t-e  log to stderr also\n");
    fprintf(stderr, "\t-l  level (a=ALERT; c=CRIT; d=DEBUG; e=ERR;\n");
    fprintf(stderr, "\t\t\ti=INFO; m=EMERG; n=NOTICE; w=WARNING;)\n");
    exit(EXIT_FAILURE);

}
