# DEBUG = -O0 -g
CFLAGS_AUX = -lcrypt
TOPDIR = ..
EXECS = intquit mykill sigsender sigreceiver ignore_pending_sig sigjmp \
	sigaltstack sigqueue catch_rtsigs sigsuspend

.include "$(TOPDIR)/bsdman2.mk"
