# DEBUG = -O0 -g

# for posixtmr_sigevsig and posixtmr_sigevthr
CFLAGS_AUX = -lrt -lpthread

TOPDIR = ..
EXECS = real_timer timer_read nanosleep posixtmr_sigevsig posixtmr_sigevthr

.include "$(TOPDIR)/bsdman2.mk"
